version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 10
    assignees:
      - "@TarekNajem04"
    labels:
      - "dependencies"
      - "nuget"
    groups:
      nuget-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    assignees:
      - "@TarekNajem04"
    labels:
      - "dependencies"
      - "actions"
    groups:
      actions-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
