<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputPath>..\..\artifacts\</OutputPath>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <!--
        Package Version Strategy
        1.0.0  initial release
        1.0.1  bug fix
        1.2.0  new features
        1.1.1  bug fix
        2.0.0  breaking change        
        -->
        <Version>1.4.0</Version>

        <Description>
            A high-performance, deterministic file discovery and filtering engine for .NET, combining GitIgnore, Glob, and Regex pattern languages into a unified matcher architecture.
        </Description>

        <PackageDescription>
            A high-performance, deterministic file discovery and filtering engine for .NET, combining GitIgnore, Glob, and Regex pattern languages into a unified matcher architecture.
        </PackageDescription>

        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <Compile Update="Resources\Strings.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Strings.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Resources\Strings.resx">
            <LastGenOutput>Strings.Designer.cs</LastGenOutput>
            <Generator>ResXFileCodeGenerator</Generator>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Jeninnet.FileQuery.DependencyInjection" />
        <InternalsVisibleTo Include="Jeninnet.FileQuery.CommandLine" />
        <InternalsVisibleTo Include="Jeninnet.FileQuery.Benchmarks" />
        <InternalsVisibleTo Include="Jeninnet.FileQuery.Tests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>
