<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <!--
        Package Version Strategy
        1.0.0  initial release
        1.2.0  new features
        1.1.1  bug fix
        2.0.0  breaking change        
        -->
        <Version>1.5.0</Version>
        <RootNamespace>Jeninnet.FileQuery.Samples</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Jeninnet.FileQuery\Jeninnet.FileQuery.csproj" />
        <ProjectReference Include="..\..\src\Jeninnet.FileQuery.CommandLine\Jeninnet.FileQuery.CommandLine.csproj" />
        <ProjectReference Include="..\..\src\Jeninnet.FileQuery.DependencyInjection\Jeninnet.FileQuery.DependencyInjection.csproj" />
    </ItemGroup>

</Project>
