<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsTestProject>true</IsTestProject>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup>
        <!-- Enable the settings and folder builder directly in the project's root directory. -->
        <RunSettingsFilePath>$(MSBuildProjectDirectory)\.runsettings</RunSettingsFilePath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.msbuild">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="MSTest" />
        <PackageReference Include="MSTest.TestAdapter" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\samples\AdvancedUsage\AdvancedUsage.csproj" />
    </ItemGroup>

</Project>