<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <!--
        Package Version Strategy
        1.0.0  initial release
        1.1.0  new features
        1.1.1  bug fix
        2.0.0  breaking change        
        -->
        <Version>1.1.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Jeninnet.FileQuery\Jeninnet.FileQuery.csproj" />
    </ItemGroup>

</Project>
